# Generated by Django 3.0.6 on 2020-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'female'), (2, 'male')], default=2, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user_name', max_length=64, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.TextField(default='user_surname', max_length=64, verbose_name='surname'),
        ),
    ]
