# Generated by Django 3.0.6 on 2020-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_imgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_profile_pic',
            field=models.BooleanField(default=False, verbose_name='is_profile'),
        ),
    ]
